### ISSUE TITLE
sprawdzić czy działa prawidłowo RestController [0.5]

### ISSUE THREAD

**Issue by MIKOLAJW197** [IOProject2018/TextTransformerApp#1]

**Comment by Glorf** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [AA](https://trello.com/c/HipPSgcA/1-aa)

**Comment by Glorf** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Jako twórca aplikacji mogę wywołać transformację zdalnie poprzez REST, aby móc zintegrować narzędzie z moimi innymi aplikacjami [15]](https://trello.com/c/HipPSgcA/1-jako-tw%C3%B3rca-aplikacji-mog%C4%99-wywo%C5%82a%C4%87-transformacj%C4%99-zdalnie-poprzez-rest-aby-m%C3%B3c-zintegrowa%C4%87-narz%C4%99dzie-z-moimi-innymi-aplikacjami-1)
