### ISSUE TITLE
Dodać rozwninięcie itd. -> i tym podobne [0.5]

### ISSUE THREAD

**Issue by MIKOLAJW197** [IOProject2018/TextTransformerApp#13]

**Comment by Glorf** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Jako użytkownik mogę o zamieniać wybrane (predefiniowane) słowa na skróty](https://trello.com/c/CECzUPrL/11-jako-u%C5%BCytkownik-mog%C4%99-o-zamienia%C4%87-wybrane-predefiniowane-s%C5%82owa-na-skr%C3%B3ty)

**Comment by Glorf** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Jako użytkownik mogę rozwijać wybrane skróty do pełnych postaci [10]](https://trello.com/c/PDZn1qmG/12-jako-u%C5%BCytkownik-mog%C4%99-rozwija%C4%87-wybrane-skr%C3%B3ty-do-pe%C5%82nych-postaci-10)
