### ISSUE TITLE
Dodać przekształcanie tekstu do formatu wspieranego przez Latex [2.0]

### ISSUE THREAD

**Issue by MIKOLAJW197** [IOProject2018/TextTransformerApp#15]

**Comment by Glorf** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Jako użytkownik mogę przekształcać tekst do formatu wspieranego przez Latex [2]](https://trello.com/c/5So3tDg1/13-jako-u%C5%BCytkownik-mog%C4%99-przekszta%C5%82ca%C4%87-tekst-do-formatu-wspieranego-przez-latex-2)
