### ISSUE TITLE
Dodać eliminacje powtarzających się słów [3.0]

### ISSUE THREAD

**Issue by MIKOLAJW197** [IOProject2018/TextTransformerApp#16]

**Comment by Glorf** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Jako użytkownik mogę eliminować powtarzające się wyrazy w bezpośrednim sąsiedztwie](https://trello.com/c/35a5P4y4/14-jako-u%C5%BCytkownik-mog%C4%99-eliminowa%C4%87-powtarzaj%C4%85ce-si%C4%99-wyrazy-w-bezpo%C5%9Brednim-s%C4%85siedztwie)
