### ISSUE TITLE
Dodać Zamiane liczb zmiennoprzecinkowych na słowa [2.0]

### ISSUE THREAD

**Issue by MIKOLAJW197** [IOProject2018/TextTransformerApp#7]

**Comment by Glorf** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Jako użytkownik mogę zamieniać liczby na tekst w języku polskim (Wpłać 100 złotych -> wpłać sto złotych) – wsparcie zakresu liczb do negocjacji](https://trello.com/c/EyRPfKf0/10-jako-u%C5%BCytkownik-mog%C4%99-zamienia%C4%87-liczby-na-tekst-w-j%C4%99zyku-polskim-wp%C5%82a%C4%87-100-z%C5%82otych-wp%C5%82a%C4%87-sto-z%C5%82otych-wsparcie-zakresu-liczb-do-ne)
