### ISSUE TITLE
Zwiniecie skrótu "na przyklad" -> np. [1.0]

### ISSUE THREAD

**Issue by MIKOLAJW197** [IOProject2018/TextTransformerApp#8]

**Comment by Glorf** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Jako użytkownik mogę o zamieniać wybrane (predefiniowane) słowa na skróty](https://trello.com/c/CECzUPrL/11-jako-u%C5%BCytkownik-mog%C4%99-o-zamienia%C4%87-wybrane-predefiniowane-s%C5%82owa-na-skr%C3%B3ty)
